// <auto-generated />
using System;
using FarmManagement.Modules.Farm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmManagement.Modules.Farm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FarmDbContext))]
    [Migration("20260109144845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmManagement.Modules.Farm.Domain.Aggregates.FarmAggregate.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Farms", (string)null);
                });

            modelBuilder.Entity("FarmManagement.Modules.Farm.Domain.Aggregates.FarmAggregate.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Fields", (string)null);
                });

            modelBuilder.Entity("FarmManagement.Modules.Farm.Domain.Aggregates.FarmAggregate.Farm", b =>
                {
                    b.OwnsOne("FarmManagement.Modules.Farm.Domain.ValueObjects.FarmName", "Name", b1 =>
                        {
                            b1.Property<Guid>("FarmId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Name");

                            b1.HasKey("FarmId");

                            b1.ToTable("Farms");

                            b1.WithOwner()
                                .HasForeignKey("FarmId");
                        });

                    b.OwnsOne("FarmManagement.Modules.Farm.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("FarmId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("FarmId");

                            b1.ToTable("Farms");

                            b1.WithOwner()
                                .HasForeignKey("FarmId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("FarmManagement.Modules.Farm.Domain.Aggregates.FarmAggregate.Field", b =>
                {
                    b.HasOne("FarmManagement.Modules.Farm.Domain.Aggregates.FarmAggregate.Farm", null)
                        .WithMany("Fields")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FarmManagement.Modules.Farm.Domain.Aggregates.FarmAggregate.Farm", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
