// <auto-generated />
using System;
using FarmManagement.Modules.Advisory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmManagement.Modules.Advisory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdvisoryDbContext))]
    [Migration("20260109143908_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmManagement.Modules.Advisory.Domain.Aggregates.AdvisoryReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdvisoryReports");
                });

            modelBuilder.Entity("FarmManagement.Modules.Advisory.Domain.Aggregates.AdvisoryReport", b =>
                {
                    b.OwnsOne("FarmManagement.Modules.Advisory.Domain.ValueObjects.PestRiskLevel", "PestRiskLevel", b1 =>
                        {
                            b1.Property<Guid>("AdvisoryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Level")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PestRiskLevel");

                            b1.HasKey("AdvisoryReportId");

                            b1.ToTable("AdvisoryReports");

                            b1.WithOwner()
                                .HasForeignKey("AdvisoryReportId");
                        });

                    b.Navigation("PestRiskLevel")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
