// <auto-generated />
using System;
using FarmManagement.Modules.Crop.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CropDbContext))]
    [Migration("20260109143856_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmManagement.Modules.Crop.Domain.Aggregates.CropCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpectedHarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PlantingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CropCycles", (string)null);
                });

            modelBuilder.Entity("FarmManagement.Modules.Crop.Domain.Aggregates.CropCycle", b =>
                {
                    b.OwnsOne("FarmManagement.Modules.Crop.Domain.ValueObjects.CropType", "CropType", b1 =>
                        {
                            b1.Property<Guid>("CropCycleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CropCode")
                                .HasColumnType("int")
                                .HasColumnName("CropCode");

                            b1.Property<int>("DurationDays")
                                .HasColumnType("int")
                                .HasColumnName("DurationDays");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CropName");

                            b1.Property<string>("TypicalStages")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("TypicalStages");

                            b1.HasKey("CropCycleId");

                            b1.ToTable("CropCycles");

                            b1.WithOwner()
                                .HasForeignKey("CropCycleId");
                        });

                    b.OwnsOne("FarmManagement.Modules.Crop.Domain.ValueObjects.YieldRecord", "YieldRecord", b1 =>
                        {
                            b1.Property<Guid>("CropCycleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("HarvestDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("HarvestDate");

                            b1.Property<float>("Quantity")
                                .HasColumnType("real")
                                .HasColumnName("YieldQuantity");

                            b1.Property<int>("Unit")
                                .HasColumnType("int")
                                .HasColumnName("YieldUnit");

                            b1.HasKey("CropCycleId");

                            b1.ToTable("CropCycles");

                            b1.WithOwner()
                                .HasForeignKey("CropCycleId");
                        });

                    b.Navigation("CropType")
                        .IsRequired();

                    b.Navigation("YieldRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
